### ISSUE TITLE
Unable to connect with transport TCP under "use your SIP account"

### ISSUE THREAD

**Issue by durdur45** [BelledonneCommunications/linhome-android#1]
I'm unable to connect to my flexisip server with "use your sip account" option in assistant :

Connection to server is always established with UDP transport regardless of transport selection UDP/TCP/TLS in assistant.
Also unable to specify a non-standard port inside proxy field.

I didn't find another place to report this issue as code is hosted on your own gitlab

**Comment by cdeschambc** [comment]
Hello, 
Thank you for your bug report. This is indeed the appropriate place :-). 
We are in the process of mirroring the code to github.
Regarding the two points your raised : 
- transport : yes we have a known bug around specifying the transport, this will be fixed in the upcoming version
- regarding specifying the port through the proxy field this is currently not possible, but it will also be added in the next version.

regards,

**Comment by cdeschambc** [comment]
fixed in 1.1
