### ISSUE TITLE
Firebase configuration

### ISSUE THREAD

**Issue by robertcoroianu** [BelledonneCommunications/linhome-android#32]
Hello,
        I'm trying to use linhome application with our Flexisip server. 
        What I want is for a user to log in with a SIP account (Flexisip) that was configured to send push notifications using Firebase to wake up the application.
        I succeeded to clone the project, replace the google service file, run in it into debug mode video calls etc. work but I do not receive push notifications when the app is closed.
        Do you have any suggestions?

Thank you.

**Comment by cdeschambc** [comment]
Hello,
Apologies for the delayed response and thank you for your interest in Linhome.
From your message it looks you are doing the necessary steps. 
Make sure you update the domain the app to match your own domain otherwise the app will see the account as 3rd party sip account and go into a dependent proxy config (automatic creation of push account on sip.linhome.org). 
Since this issue is fairly old (again apologies for the very late reply) I am closing this. But if still accurate please reopen, and if you need further assistance you can contact our teams team on https://www.linhome.org/contact/
regards
